# Generated by Django 6.0.1 on 2026-01-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
